parameters:
    predator_num: 1000
    prey_num: 500
    num_actions: 4
    height: 600
    damage_per_step: 0.01
    img_length: 5
    max_hunt_square: 5
    max_speed: 1
    max_acceleration: 1
    width: 600
    batch_size: 512
    vision_width: 7
    vision_height: 7
    max_health: 1.0
    min_health: 0.5
    max_crossover: 3
    wall_prob: 0.005
    wall_seed: 20
    food_prob: 0
    prey_increase_prob: 0.006
    predator_increase_prob: 0.001
    crossover_scope: 5

    # models
    learning_rate: 0.001
    #input_dim: 55
    input_dim: 7
    #hidden_dims: [32, 32]
    hidden_dims: [16, 8]
    action_size: 4
    agent_emb_dim: 3
    gamma: 0.99

    # training
    episodes: 100
    batch_size: 64
    episode_step: 500
    random_step: 5000
    min_greedy: 0.3
    max_greedy: 0.9
    greedy_step: 6000
    update_period: 20

    # test
    test_step: 200000
    #obs_type: 'dense' #conv
    obs_type: 'conv' #conv

    video_flag: False

    cpu_cores: 5
