parameters:
    predator_num: 1000
    prey_num: 1000
    num_actions: 4
    height: 600
    width: 600
    damage_per_step: 0.01
    img_length: 5
    max_hunt_square: 5
    max_speed: 1
    max_acceleration: 1
    batch_size: 512
    vision_width: 15
    vision_height: 15
    max_health: 1.0
    min_health: 0.5
    wall_prob: 0.005
    wall_seed: 20
    food_prob: 0
    prey_increase_prob: 0.006
    predator_increase_prob: 0.003
    health_increase_rate: 2
    increase_every: 1
    time_step: 4

    # models
    learning_rate: 0.001
    #input_dim: 55
    input_dim: 4
    hidden_dims: [32, 64, 256]
    #hidden_dims: [16, 8]
    action_size: 4
    agent_emb_dim: 5
    gamma: 0.99
    lstm_input: 256
    lstm_out: 256

    # training
    episodes: 500
    batch_size: 128
    episode_step: 500
    random_step: 5000
    min_greedy: 0.005
    max_greedy: 0.99
    greedy_step: 100000
    update_period: 4

    # test
    test_step: 200000
    obs_type: 'conv' #conv
    #obs_type: 'dense' #conv

    video_flag: False

    cpu_cores: 4

    load_weight:
    multiprocessing: True

    # Reward Setting
    get_closer_reward: 0


