parameters:
    predator_num: 1000
    prey_num: 1000
    num_actions: 5
    height: 700
    width: 700
    damage_per_step: 0.01
    img_length: 5
    max_hunt_square: 5
    max_speed: 1
    max_acceleration: 1
    batch_size: 512
    vision_width: 27
    vision_height: 27
    max_health: 1
    min_health: 0.5
    max_crossover: 3
    wall_prob: 0.005
    wall_seed: 20
    food_prob: 0
    prey_increase_prob: 0.7
    predator_increase_prob: 0.7
    crossover_scope: 11
    health_increase_rate: 3
    increase_every: 1

    # models
    learning_rate: 0.001
    #input_dim: 55
    input_dim: 7
    hidden_dims: [32, 32]
    #hidden_dims: [16, 8]
    agent_emb_dim: 3
    gamma: 0.99

    # training
    episodes: 10000
    batch_size: 128
    episode_step: 500
    random_step: 5000
    min_greedy: 0.3
    max_greedy: 0.9
    greedy_step: 15000
    update_period: 4

    # test
    test_step: 200000
    obs_type: 'conv' #conv
    #obs_type: 'dense' #conv

    video_flag: False

    cpu_cores: 4

    load_weight:
    multiprocessing: True

    # Reward Setting
    get_closer_reward: 0.2
