parameters:
    predator_num: 2000
    prey_num: 2000
    num_actions: 4
    height: 500
    damage_per_step: 0.01
    img_length: 5
    max_hunt_square: 5
    width: 500
    batch_size: 256
    vision_width: 27
    vision_height: 27
    max_health: 1.0
    min_health: 0.5
    wall_prob: 0.005
    wall_seed: 20
    food_prob: 0
    prey_increase_prob: 0.006
    predator_increase_prob: 0.003
    crossover_scope: 15
    health_increase_rate: 2
    increase_every: 1
    max_predator_offsprings: 1
    max_prey_offsprings: 1
    time_step: 4
    predator_capacity: 8000
    prey_capacity: 8000
    min_attack: 1
    max_attack: 4
    min_resilience: 1
    max_resilience: 4
    min_speed: 1
    max_speed: 4
    mutation_prob: 0.001

    learning_rate: 0.00001
    #input_dim: 55
    input_dim: 7
    hidden_dims: [32, 64, 256]
    #hidden_dims: [16, 8]
    action_size: 4
    agent_emb_dim: 5
    gamma: 0.99
    lstm_input: 1024
    lstm_out: 256

    # training
    episodes: 500
    batch_size: 128
    episode_step: 500
    random_step: 5000
    min_greedy: 0.3
    #min_greedy: 0.005
    max_greedy: 0.9
    #greedy_step: 100000
    greedy_step: 20000
    update_period: 100

    # test
    test_step: 200000
    #obs_type: 'conv_with_id' #conv
    obs_type: 'conv' #conv

    video_flag: False

    cpu_cores: 4

    #load_weight: './results/simple_population_dynamics_ga/exp_20/models/model_405.h5'
    #load_weight: './results/complex_population_dynamics/exp_9/models/model_45.h5'
    #load_weight: './results/simple_population_dynamics_ga/exp_21/models/model_200.h5'
    #load_weight:  './results/simple_population_dynamics_ga/exp_21/models/model_79.h5'
    #load_weight: './results/complex_population_dynamics/exp_17/models/model_120.h5'
    load_weight:
    multiprocessing: True

    # Reward Setting
    get_closer_reward: 0

    min_crossover_age: 100
    is_embedding: False
