parameters:
    predator_num: 2000
    prey_num: 1000
    num_actions: 4
    height: 400
    damage_per_step: 0.01
    img_length: 5
    max_hunt_square: 5
    max_speed: 1
    max_acceleration: 1
    width: 400
    batch_size: 512
    vision_width: 10
    vision_height: 10
    max_health: 1.0
    min_health: 0.5
    max_crossover: 3
    wall_prob: 0.005
    wall_seed: 20
    food_prob: 0
    prey_increase_prob: 0.01
    predator_increase_prob: 0.005
    crossover_scope: 3
    health_increase_rate: 4
    increase_every: 1

    # models
    learning_rate: 0.001
    input_dim: 55
    #input_dim: 7
    #hidden_dims: [32, 32]
    hidden_dims: [16, 8]
    action_size: 4
    agent_emb_dim: 3
    gamma: 0.99

    # training
    episodes: 500
    batch_size: 128
    episode_step: 500
    random_step: 5000
    min_greedy: 0.3
    max_greedy: 0.9
    greedy_step: 15000
    update_period: 4

    # test
    test_step: 200000
    #obs_type: 'conv' #conv
    obs_type: 'dense' #conv

    video_flag: False

    cpu_cores: 4

    #load_weight: ./results/exp_10/models/model_99.h5
    load_weight:
    multiprocessing: True
